CREATE TABLE Attendance(
    SessionID INTEGER NOT NULL REFERENCES Session(SessionID),
    USFSN INTEGER NOT NULL REFERENCES Member(USFSN),
    PRIMARY KEY (SessionID, USFSN),
    FOREIGN KEY (SessionID) REFERENCES Session(SessionID)
    	ON DELETE CASCADE ON UPDATE NO ACTION,
     FOREIGN KEY (USFSN) REFERENCES Member(USFSN)
    	ON DELETE CASCADE ON UPDATE NO ACTION
);