CREATE TABLE Member(
    USFSN INTEGER NOT NULL PRIMARY KEY,
    FirstName VARCHAR(35) NOT NULL,
    LastName VARCHAR(35) NOT NULL,
    Email VARCHAR(60) NOT NULL,
    Phone CHAR(10) NOT NULL,
    Coach VARCHAR(70) NOT NULL,
    IsMember BOOLEAN NOT NULL
);